[package]
name = "baihua-client-gui"
version = "0.1.0-alpha.1"
edition = "2024"

[[bin]]
name = "baihua-client-gui"
path = "src/main.rs"

[dependencies]
baihua-core = { path = "../baihua-core" }
eframe = { version = "0.36.1", default-features = false, features = ["glow", "default_fonts", "x11", "wayland"] }
egui = "0.36.1"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
serde_json = "1"
tungstenite = "0.30.0"
http = "1"
chrono = { version = "0.4.45", features = ["clock"] }
notify-rust = "4"
ed25519-dalek = { version = "3", features = ["rand_core"] }
x25519-dalek = { version = "3", features = ["static_secrets"] }
